# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c15486ef2661576a35e6800efe2aadf1fdb076bdc48ecfcd0801d136976c9c0be96facd2f0bbfe29b4c1c7b78bec56ff36c70537bafa76886ea7045bca4fa05

test:
  secret_key_base: 0b44c296bc32e5739ecb96e7f7fb86e58746230ebbfc2191f148c941ecf846444cd8f6e1a987de116b69d2691e33e11da99c9712ca0b620926f7ef87b74d623c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
